### PR TITLE
Add icon and alphabetize country list

### LINKED ISSUE #1: 2 small sophistications
Hi @lachhebo !

First of all I would like to thanks for this plugin! It has almost alll the information and settings what the subject needs.

But would like to suggest 2 small sophistications:

1. Please sort in ABC the country list in the drop down as currently the 'random' sorting is very hard to use.
2. Please use one icon for the extension itself on the Gnome panel instead of Covid-19 name as it's a little bit too long and visually off between the further icons. For example there is one simply usable for it: https://materialdesignicons.com/icon/virus

Thanks for your efforts!

### PR DESCRIPTION
**Pull request by jpsnyder**
Hi, thanks for making this extension. It's a simple way to keep track in these unfortunate times.

This request solves the following I took the liberty in tackling:
- closes #1 
- Removes the unknown box icons i noticed when "empty" was used.
- Adds a refresh button

### CODE REVIEW

**Comment by lachhebo** [comment]
Thanks a lot :)

**Review by Tamas-Toth-ebola — COMMENTED** [review]
Hi @jpsnyder !

Thanks for your fast response the required sophistications. Just one question. Could be the virus icon vector icon to make it more perfectly on HDPI monitors? An SVG icon would be perfect.

Thanks for your effort!

**Comment by jpsnyder** [comment]
@Tamas-Toth-ebola Thanks, but I am not quite sure how. I simply used the icon that you linked to. However, the .svg file provided was completely black which will not work on most default gnome shell themes. Therefore, I went for the png in which I could specify white. 
If you can figure out how to get a white svg icon, it should simply be the matter of updating the file name in `stylesheet.css`

**Comment by Tamas-Toth-ebola** [comment]
Hi!

As I'm not a real developer the whole background for me also unknown just I know that Gnome globally can and uses SVG icons everywhere. Almost all iconsets, icon themes nowadays are pure SVG, and also not just icon themes but the Gnome Shell extensions also use them directly.

How I try to help on the problem is the SVG file itself. What you downloaded from the MDI Icons is a pure black SVG icon as they offer SVG icons such way. But those icons as they are in vector format can problemless recolored without quality loss. So I made you a Gnome 'normal' panel icon color version of the MDI original. Attached here: https://github.com/lachhebo/corona-tracker/files/4416443/virus.zip

The only difference compared to for example Caffeine is that the others use 16px version while this one is 24px. But as SVG is basically vector format these size definitions is just meta data as the OS or the app could render it in any required size.

Please try to use it, if you have any problem tell me and will try to help on it (I could resize to 16px for you if the current one will fail.).

Thanks for your continuous efforts!

**Comment by Tamas-Toth-ebola** [comment]
For any help you can check eg.: Caffeine to see how it uses the SVG icons: https://github.com/eonpatapon/gnome-shell-extension-caffeine

_(Of course just if you have some time for it...)_

**Comment by jpsnyder** [comment]
Thanks. Resizing isn't necessary because it is svg as you said and the `stylesheet.css` will resize it for you.

Thanks for the icon, but it looks like the icon is still a bit dark. Are you able to brighten it some more?
image

**Comment by Tamas-Toth-ebola** [comment]
Ok! To make the whole thing the most possible perfect, I red some informations about Gnome icon usage, and here are the results:

https://developer.gnome.org/hig/stable/icons-and-artwork.html.en

> Symbolic icons are simple and monochrome, and are designed to work well at smaller sizes. They are defined as 16✕16px SVGs, and can be scaled to multiples of 16 (such as 32✕32, 64✕64, 128✕128). Symbolic icons **generally have a neutral color, although their color can be changed programmatically**.

https://developer.gnome.org/hig/stable/icon-design.html.en

>Symbolic icons have a simple form and are drawn within a **16×16 pixel grid**. They are then **programmatically scaled and colored** within the user interface itself.

>While symbolic icons are scalable and should work at any size, the basic canvas size is **16×16 grid** units. **You have the whole canvas to fill**, but note that a filled rectangular object will appear stronger/larger when placed next to items that only use thinner strokes.

So the color of the used icon in theory is indifferent as the whole GUI should recolor it according to actually used Gnome Shell theme. In reality it really is, check my screenie:

image

What you can see that the **Variety**, **Slack**, **Viber** are really not standard Gnome Shell extensions as they are really not that. They are normal applications with 'tray icons' what are really not aligned correctly to the environment. But almost all the other things use almost the same visuals. Same color, same size, same style. **Sadly my Docker extension is (also) wrong**, would be lot more nice with proper 16px 'rasterized' and properly recolored by the Gnome Shell itself.

Some of them use system icons (As **Brightness control using ddcutil** has `display-brightness-symbolic` link in itself.) but others have custom own icons (As **Caffeine**, or **New Apt Update Indicator** has their own icons in the extension's folder.). The extensions with custom icons sometime use totally different color compared to each other but also compared to the actual system. In this case the guideline is really true as those icons use the color of the Shell theme instead of themselves.

What I gave you last time was a 24px version as MDI icons use this raster grid instead of Gnome's 16px suggestion. With vector icons this from one aspect is not problem as the resource will be rendered by runtime to the required physical resolution but from another aspect could be problem as the 24px icon could have more details what a 16px raster grid could handle therefore the result will be not so sharp and nice because the less of the details. Anyway as the icon is not mine we could not do anything with it. It will show what it can we will not redraw to align it's content to 16px grid. (Moreover on HDPI screens this slightly visible problem will be gone.)

The original icon has som margin on the 24px grid while Gome suggest to use the whole 16px grid, and in this case **I made a new one with cut those margins to justify the resolution potential.**

The color what I used is from **Caffeine**'s original icon but basically should use one of the Gnome neutral colors from the link above, and but the color basically has no real goals as the Shell needs to recolor it as we can seem on my screenie above. Anyway **Caffeine**'s color is almost in the line of Gnome's own neutral palette. **Now I changed it to the middle of the neutral palette from the guideline.**

Could you please check in the following extension that how they use their icons to allow the system to recolor it homogeneously with the others?

https://github.com/eonpatapon/gnome-shell-extension-caffeine
https://github.com/kazysmaster/gnome-shell-extension-lockkeys
https://github.com/HamburgerJungeJr/new-apt-update-indicator

Of course if you have no time, it's absolutely understandable, but if have some with these method would be the perfect solution.

**Here is the new one with the mentioned differences:** [virus.zip](https://github.com/lachhebo/corona-tracker/files/4421223/virus.zip)

Thanks for your effort!

**Comment by Tamas-Toth-ebola** [comment]
@jpsnyder hi!

Last night I made all the requested changes on the panel icon so I made a pull requests with them.

Hope you like it as the icon now have already blended totally between the others from size and also from color aspect.

**Comment by jpsnyder** [comment]
@Tamas-Toth-ebola sorry I am just getting back to this. Your update looks good. Thanks for figuring this out!

**Comment by Tamas-Toth-ebola** [comment]
@jpsnyder there is really not problem about it. It had made for me a challenge as I'm not knowing to much about JavaScript and never touched any Gnome Shell extension. So it was a mission:) what i had needed to complete. I'm glad that it was successful and also glad if both of you were also satisfied with that.

**Pull request merged**
