### PR TITLE
Finalize proper panel icon & some minor polishing

### PR DESCRIPTION
**Pull request by Tamas-Toth-ebola**
Hi!

While I'm not a developer and this is my very first pull request in my life last night I tried to finalize the proper panel icon with success and made some more minor corrections to get the most correct results with the extension.

**Check my changes and if it's correct for you please merge it and if possible please update it on extensions.gnome.org.**

Thanks for your effort!

### CODE REVIEW

**Comment by Tamas-Toth-ebola** [comment]
Some more polishing in the README with official Gnome like screenshot.

**Comment by Tamas-Toth-ebola** [comment]
And one more:) Sorry, I will stop it...

**Comment by lachhebo** [comment]
Hi, thank you for your work @Tamas-Toth-ebola, you did a great job. I will update the extension in extensions.gnome.org right away. The updated extension should be available in a few days.

**Comment by Tamas-Toth-ebola** [comment]
Thank you!

**Pull request merged**
